# Generated by Django 4.0 on 2022-02-20 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_init_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=uuid.uuid4)),
                ('status', models.CharField(choices=[('COMPLETE', 'complete'), ('CANCELED', 'canceled'), ('IN_PROGRESS', 'in_progress'), ('REQUESTED', 'requested'), ('RESCHEDULED', 'rescheduled'), ('SCHEDULED', 'scheduled'), ('STARTED', 'started')], default='REQUESTED', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apts_as_clin', to='users.user')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apts_as_patient', to='users.user')),
            ],
        ),
    ]
