# Generated by Django 4.0 on 2022-03-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_uuid_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
