# Generated by Django 4.0 on 2022-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_lat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_lon',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
