# Generated by Django 4.0 on 2022-04-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_lat_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_lon',
        ),
    ]
