# Generated by Django 4.0 on 2022-02-17 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_init_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ARRIVED', 'arrived'), ('CANCELED', 'canceled'), ('IN_PROGRESS', 'in_progress'), ('REQUESTED', 'requested'), ('RESCHEDULED', 'rescheduled'), ('SCHEDULED', 'scheduled')], default='REQUESTED', max_length=40)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_as_driver', to='users.user')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_as_patient', to='users.user')),
            ],
        ),
    ]
